---
blank_issues_enabled: false
contact_links:
  - name: Amazing GitHub Template Community Support
    url: https://github.com/dec0dOS/amazing-github-template/discussions
    about: Please ask and answer questions here.
